name: Create Release Candidate
on:
  workflow_call:

permissions:
  packages: write
  contents: write

jobs:
    preRelease:
      name: preRelease code
      runs-on: ubuntu-latest
      steps:
        #Para obtener la fecha actual
        - name: Get current date
          id: date
          run: echo "NOW=$(date +'%Y.%m.%d')" >> $GITHUB_ENV
        - name: Create Tag para Github
          id: create_release
          uses: actions/create-release@v1
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
          with:
            tag_name: "${{ env.NOW }}-RC-${{ github.run_number }}" #Se le asigna un tag con la nomenclatura solicitada
            prerelease: true
            #release_name: Release ${{ steps.date.outputs.date }}-RC[${{ github.run_number }}] #Comentado para ver si no hace release

        # Guardar el valor de NOW en una salida
        - name: Set output
          id: set_output
          run: echo "::set-output name=now::${{ env.NOW }}"

    
    env-setup:
      name: Configuración de environment
      runs-on: ubuntu-latest
      needs: preRelease
      steps:
        - name: Use tag_name from preRelease
          run: |
            echo "Tag name from preRelease job: ${{ needs.preRelease.outputs.now }}"
        - name: Crear branch policy
          env:
            OWNER: ${{ secrets.OWNER }}
            REPO: ${{ secrets.REPO }}
            ENV: ${{ secrets.ENV }}
            TOKEN: ${{ secrets.TOKEN }}
          run: |
            curl -L \
              -X POST \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer $TOKEN" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              https://api.github.com/repos/$OWNER/$REPO/environments/$ENV/deployment-branch-policies \
              -d '{"name":"${{ needs.preRelease.outputs.date }}-RC-${{ github.run_number }}"}'
