name: Release Pipeline
on:
  push:
    branches: 
      - 'main'
    paths-ignore:
      - '.github/**'

  workflow_dispatch:

permissions:
  packages: write
  contents: write

jobs:
    preRelease:
      if: ${{ github.event_name == 'push' }}
      uses: stuvms/stuvms.github.io/.github/workflows/preRelease.yml@main

    Release:
      uses: stuvms/stuvms.github.io/.github/workflows/release.yml@main